#!/usr/bin/env python3
"""Generates the mushaf layout from Tanzil's Quran metadata.

Until 1.8.0 these tables were 1,268 hand-typed integers covering only pages and juz, guarded by
three spot checks. They now come from the same source as the text, carry the hizb, rub', manzil
and ruku divisions as well, and are checked exhaustively against a golden table.

Usage:
    python3 scripts/quran/build_layout.py [--cache DIR]

Writes:
    app/src/main/java/.../data/quran/MushafLayout.kt   the tables the app reads
    app/src/test/resources/mushaf-layout.json          the same tables, for the test to compare against

Source:
    https://tanzil.net/res/text/metadata/quran-data.xml  (Tanzil Project, CC BY 3.0)
"""
import argparse
import json
import pathlib
import sys
import urllib.request
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parents[2]
KOTLIN = ROOT / "app/src/main/java/com/pilotothegreat/deencompanion/data/quran/MushafLayout.kt"
GOLDEN = ROOT / "app/src/test/resources/mushaf-layout.json"
URL = "https://tanzil.net/res/text/metadata/quran-data.xml"

EXPECTED = {"juzs": 30, "hizbs": 240, "manzils": 7, "rukus": 556, "pages": 604, "sajdas": 15}


def fetch(cache: pathlib.Path) -> pathlib.Path:
    cache.mkdir(parents=True, exist_ok=True)
    path = cache / "quran-data.xml"
    if not path.exists():
        print("downloading quran-data.xml")
        request = urllib.request.Request(URL, headers={"User-Agent": "bilal-build-script"})
        with urllib.request.urlopen(request, timeout=120) as response:
            path.write_bytes(response.read())
    return path


def starts(root: ET.Element, tag: str) -> list[list[int]]:
    return [[int(e.get("sura")), int(e.get("aya"))] for e in root.find(tag)]


def kotlin_table(name: str, doc: str, pairs: list[list[int]], per_row: int = 8) -> str:
    rows = []
    for i in range(0, len(pairs), per_row):
        rows.append("        " + "  ".join(f"{s}, {a}," for s, a in pairs[i:i + per_row]))
    body = "\n".join(rows)
    return f"    /** {doc} */\n    val {name}: IntArray = intArrayOf(\n{body}\n    )\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cache", default="/tmp/bilal-quran")
    args = parser.parse_args()
    root = ET.parse(fetch(pathlib.Path(args.cache))).getroot()

    for tag, count in EXPECTED.items():
        found = len(root.find(tag))
        if found != count:
            print(f"{tag}: expected {count}, found {found}", file=sys.stderr)
            return 1

    tables = {tag: starts(root, tag) for tag in ("pages", "juzs", "hizbs", "manzils", "rukus")}
    sajdas = [
        {"surah": int(e.get("sura")), "ayah": int(e.get("aya")), "obligatory": e.get("type") == "obligatory"}
        for e in root.find("sajdas")
    ]
    # Ordering is what every lookup here relies on: each table is a sorted list of starts.
    for tag, pairs in tables.items():
        if pairs != sorted(pairs):
            print(f"{tag} is not in mushaf order", file=sys.stderr)
            return 1

    body = "".join([
        kotlin_table("pageStarts", "(surah, ayah) pairs, one per page starting at page 1.", tables["pages"]),
        "\n",
        kotlin_table("juzStarts", "(surah, ayah) pairs, one per juz starting at juz 1.", tables["juzs"]),
        "\n",
        kotlin_table(
            "quarterStarts",
            "(surah, ayah) pairs, one per rub' al-hizb: four to a hizb, eight to a juz.",
            tables["hizbs"],
        ),
        "\n",
        kotlin_table("manzilStarts", "(surah, ayah) pairs, one per manzil: the seven-day reading cycle.", tables["manzils"]),
        "\n",
        kotlin_table("rukuStarts", "(surah, ayah) pairs, one per ruku': the thematic sections marked ع.", tables["rukus"]),
    ])
    sajdah_rows = "\n".join(
        f"        Sajdah({s['surah']}, {s['ayah']}, obligatory = {'true' if s['obligatory'] else 'false'}),"
        for s in sajdas
    )

    KOTLIN.write_text(f'''package com.pilotothegreat.deencompanion.data.quran

/**
 * An ayah at which the reader prostrates. The schools differ over which prostrations are obligatory,
 * so the flag records what the mushaf marks and the reader says that scholars differ rather than
 * ruling between them.
 */
data class Sajdah(val surah: Int, val ayah: Int, val obligatory: Boolean)

/**
 * Where every division of the standard Madinah mushaf (Hafs) begins.
 *
 * Generated by scripts/quran/build_layout.py from Tanzil's quran-data.xml; do not edit by hand.
 * app/src/test/resources/mushaf-layout.json holds the same tables, and MushafLayoutTest compares
 * the two ayah by ayah.
 */
internal object MushafLayout {{
    const val EDITION = "Madinah Mushaf (Hafs), King Fahd Glorious Quran Printing Complex"
    const val PAGE_COUNT = {len(tables["pages"])}
    const val JUZ_COUNT = {len(tables["juzs"])}
    const val HIZB_COUNT = {len(tables["hizbs"]) // 4}
    const val MANZIL_COUNT = {len(tables["manzils"])}
    const val RUKU_COUNT = {len(tables["rukus"])}

{body}
    /** The fifteen ayahs of sajdat al-tilawah, in mushaf order. */
    val sajdahList: List<Sajdah> = listOf(
{sajdah_rows}
    )

    val sajdahs: Map<Pair<Int, Int>, Sajdah> = sajdahList.associateBy {{ it.surah to it.ayah }}

    /** Mushaf page (1..604) holding the ayah. */
    fun pageOf(surah: Int, ayah: Int): Int = lastStartAtOrBefore(pageStarts, surah, ayah) + 1

    /** Juz (1..30) holding the ayah. */
    fun juzOf(surah: Int, ayah: Int): Int = lastStartAtOrBefore(juzStarts, surah, ayah) + 1

    /** Rub' al-hizb (1..240) holding the ayah, counted from the start of the mushaf. */
    fun quarterOf(surah: Int, ayah: Int): Int = lastStartAtOrBefore(quarterStarts, surah, ayah) + 1

    /** Hizb (1..60) holding the ayah. */
    fun hizbOf(surah: Int, ayah: Int): Int = (quarterOf(surah, ayah) - 1) / 4 + 1

    /** Which quarter of its hizb the ayah falls in, 1 through 4. */
    fun rubOf(surah: Int, ayah: Int): Int = (quarterOf(surah, ayah) - 1) % 4 + 1

    /** Manzil (1..7) holding the ayah. */
    fun manzilOf(surah: Int, ayah: Int): Int = lastStartAtOrBefore(manzilStarts, surah, ayah) + 1

    /** Ruku' (1..556) holding the ayah. */
    fun rukuOf(surah: Int, ayah: Int): Int = lastStartAtOrBefore(rukuStarts, surah, ayah) + 1

    /** The quarter that begins exactly at this ayah, or null: what the reader marks with a ۞. */
    fun quarterStartingAt(surah: Int, ayah: Int): Int? =
        startIndexOf(quarterStarts, surah, ayah)?.plus(1)

    /** The juz that begins exactly at this ayah, or null. */
    fun juzStartingAt(surah: Int, ayah: Int): Int? = startIndexOf(juzStarts, surah, ayah)?.plus(1)

    private fun startIndexOf(starts: IntArray, surah: Int, ayah: Int): Int? {{
        val index = lastStartAtOrBefore(starts, surah, ayah)
        return index.takeIf {{ starts[index * 2] == surah && starts[index * 2 + 1] == ayah }}
    }}

    /**
     * Index of the last entry in [starts] (pairs of surah and ayah) that begins at or before the
     * ayah. The tables are sorted, so this is a binary search.
     */
    internal fun lastStartAtOrBefore(starts: IntArray, surah: Int, ayah: Int): Int {{
        var low = 0
        var high = starts.size / 2 - 1
        while (low < high) {{
            val mid = (low + high + 1) / 2
            val s = starts[mid * 2]
            val a = starts[mid * 2 + 1]
            if (s < surah || (s == surah && a <= ayah)) low = mid else high = mid - 1
        }}
        return low
    }}
}}
''', encoding="utf-8")
    print(f"wrote {KOTLIN.relative_to(ROOT)}")

    GOLDEN.parent.mkdir(parents=True, exist_ok=True)
    GOLDEN.write_text(json.dumps({
        "edition": "Tanzil quran-data.xml",
        "pages": tables["pages"],
        "juzs": tables["juzs"],
        "quarters": tables["hizbs"],
        "manzils": tables["manzils"],
        "rukus": tables["rukus"],
        "sajdas": sajdas,
    }, separators=(",", ":")) + "\n", encoding="utf-8")
    print(f"wrote {GOLDEN.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
